### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Guiorgy** [norsemangrey/zfs-health-check#2]
Please specify a license so that [others can use, change, and distribute your software](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

If you are unsure, or don't really care about the terms, the [MIT](https://opensource.org/license/mit) is small and simple, and among the most widely used and permissive licenses.

**Comment by norsemangrey** [comment]
Done! Thanks for the suggestion 👍
